# Generated by Django 5.2.17 on 2026-09-19 12:29

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Process Template',
                'verbose_name_plural': 'Process Templates',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='template_active_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectField',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Field label shown to user (e.g. "Drawing Number")', max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text (single line)'), ('textarea', 'Text Area (multi-line)'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown / Select'), ('checkbox', 'Checkbox (Yes/No)')], default='text', max_length=20)),
                ('placeholder', models.CharField(blank=True, help_text='Hint text inside the field', max_length=200)),
                ('options', models.TextField(blank=True, help_text='For Dropdown only — one option per line')),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Field',
                'verbose_name_plural': 'Project Fields',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='field_active_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectFieldValue',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='formbuilder.projectfield')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='projects.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'field'), name='fieldvalue_unique_per_project')],
            },
        ),
    ]
