# Generated by Django 5.2.17 on 2026-09-19 12:26

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=200)),
                ('machine_type', models.CharField(choices=[('CNC', 'CNC Machine'), ('VMC', 'VMC Machine'), ('BMC', 'BMC Machine'), ('LATHE', 'Lathe Machine'), ('MILLING', 'Milling Machine'), ('DRILLING', 'Drilling Machine'), ('GRINDING', 'Grinding Machine'), ('OTHER', 'Other')], max_length=20)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('specifications', models.TextField(blank=True, help_text='Technical specifications')),
                ('image', models.ImageField(blank=True, null=True, upload_to='machines/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ['machine_name'],
                'indexes': [models.Index(fields=['is_active', 'machine_name'], name='machine_active_name_idx'), models.Index(fields=['machine_type'], name='machine_type_idx')],
            },
        ),
    ]
