# Generated by Django 5.2.17 on 2026-09-19 12:26

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about this enquiry')),
            ],
            options={
                'verbose_name': 'Contact Enquiry',
                'verbose_name_plural': 'Contact Enquiries',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='enquiry_status_date_idx'), models.Index(fields=['-submitted_at'], name='enquiry_submitted_idx')],
            },
        ),
    ]
