# Generated by Django 5.2.17 on 2026-09-19 12:26

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('icon_label', models.CharField(default='⚙', help_text='Emoji or short text for icon', max_length=10)),
                ('image', models.FileField(blank=True, null=True, upload_to='services/')),
                ('features', models.TextField(blank=True, help_text='One feature per line — these appear as bullet points')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='service_active_order_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cnc', 'CNC Machining'), ('vmc', 'VMC Machining'), ('lathe', 'Lathe / Turning'), ('milling', 'Milling'), ('drilling', 'Drilling'), ('finishing', 'Finishing'), ('other', 'Other')], default='cnc', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='portfolio/%Y/%m/')),
                ('material', models.CharField(blank=True, help_text='e.g. EN24 Steel, SS304', max_length=100)),
                ('machine_used', models.CharField(blank=True, help_text='e.g. Fanuc CNC', max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on home page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Work Sample',
                'verbose_name_plural': 'Work Samples',
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['is_active', '-is_featured', '-created_at'], name='work_active_feat_idx'), models.Index(fields=['category'], name='work_category_idx')],
            },
        ),
    ]
